site_name: SamraG
site_url: https://sam2636.github.io/sam-agents/
site_description: "RAG Agent Documentation using LangGraph"
site_author: "Sam Dhanaseelan"
use_directory_urls: false 

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: material/book-open-page-variant

nav:
  - Home: index.md
  - Usage: usage.md
  - MultiGent: multigent.md
  - Studying:
      - DSA:
          - Python Basics: Python-basic.md
          - Dsa-Overview: DSA.md
          - Patterns: DSA_pattern.md
          - python-interview: python-interview.md
          - python-test-1: basics-test1.md
          - python-test-2: python-test2.md
          - python-test-3: python-test3.md
      - DSA Solutions:
          - Two-pointer: Two-pointer.md
          - Slow-fast-pointer: slow&fast-pointer.md
          - Sliding-window: sliding-window.md
  - TCS-ion:
      - TCS-ion-logical-reasoning: 
          - TCS-ion-logical-reasoning-1: Logical-reasoning-batch1.md
          - TCS-ion-logical-reasoning-2: Logical-reasoning-batch2.md
          - TCS-ion-logical-reasoning-3: Logical-reasoning-batch3.md
          - TCS-ion-logical-reasoning-4: Logical-reasoning-batch4.md
          - TCS-ion-logical-reasoning-5: Logical-reasoning-batch5.md
      - TCS-ion-math:
          - TCS-ion-math-1: Math-batch1.md
          - TCS-ion-math-2: Math-batch2.md
          - TCS-ion-math-3: Math-batch3.md
          - TCS-ion-math-4: Math-batch4.md
      - TCS-ion-verbal:
          - TCS-ion-verbal-1: Verbal-reasoning-batch1.md
          - TCS-ion-verbal-2: Verbal-reasoning-batch2.md
          - TCS-ion-verbal-3: Verbal-reasoning-batch3.md
          - TCS-ion-verbal-4: Verbal-reasoning-batch4.md
      - TCS-ion-coding:
          - TCS-ion-coding-1: coding-batch.md


plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - attr_list

site_dir: site
