site_name: LangGraph RAG
site_url: https://sam2636.github.io/sam-agents/langgraph-rag/
site_description: "RAG Agent Documentation using LangGraph"
site_author: "Sam Dhanaseelan"

# ✅ Theme configuration
theme:
  name: material
  language: en
  features:
    - navigation.instant        # Instant navigation without reload
    - navigation.tabs           # Top-level sections as tabs
    - navigation.sections       # Collapsible sections
    - navigation.expand         # Expand current section by default
    - search.suggest            # Search suggestions
    - search.highlight          # Highlight results
    - content.code.copy         # Copy button for code snippets
    - content.tabs.link         # Tabbed content linking
    - content.tooltips          # Tooltips for references
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: material/book-open-page-variant

# ✅ Navigation
nav:
  - Home: index.md
  - Usage: usage.md

# ✅ Plugins
plugins:
  - search
  - mkdocs-material
  - autorefs         # Cross-reference sections easily
  - mkdocstrings     # Auto-generate docs from Python code

# ✅ Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji   # ✅ simple form, works without materialx
  - attr_list


# ✅ Build output directory
site_dir: site

# ✅ Use directory-style URLs (/page/ instead of /page.html)
use_directory_urls: true
