site_name: SamraG
site_url: https://sam2636.github.io/sam-agents/langgraph-rag/
site_description: "RAG Agent Documentation using LangGraph"
site_author: "Sam Dhanaseelan"

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: material/book-open-page-variant

nav:
  - Home: index.md
  - Usage: usage.md
  - MultiGent: multigent.md
  - Studying:
      - DSA:
          - Python Basics: Python-basic.md
          - Dsa-Overview: DSA.md
          - Patterns: DSA_pattern.md
          - python-interview: python-interview.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - attr_list

site_dir: site
use_directory_urls: true
