.PHONY: help build serve clean

help:
	@echo "Available commands:"
	@echo "  make build   - Build the documentation"
	@echo "  make serve   - Serve locally with live reload"
	@echo "  make clean   - Clean the build directory"

build:
	mkdocs build

serve:
	mkdocs serve

clean:
	rm -rf site/
